import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "chatbot",
  description: "Generated by chatbot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen'>
          <div className=' bg-blue-200 w=1/3 pt-1'>Chat Manager</div>

          {/* メインコンテンツ */}

          <div className='w-full flex justify-center '>{children}</div>
        </div>
      </body>
    </html>
  );
}
