import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "chatbot",
  description: "Generated by chatbot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen'>
          {/* サイドバー - 幅を固定し、余白とスタイリングを追加 */}
          <div className='bg-blue-100 w-64 p-4 shadow-md'>
            <h2 className='font-bold text-lg mb-4'>Chat Manager</h2>
            {/* サイドバーのコンテンツをここに追加できます */}
          </div>

          {/* メインコンテンツエリア - 余白を追加して見やすく */}
          <div className='flex-1 p-6'>{children}</div>
        </div>
      </body>
    </html>
  );
}
