import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
export const metadata: Metadata = {
  title: "chatbot",
  description: "Generated by chatbot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen'>
          {/* サイドバー - 幅を固定し、余白とスタイリングを追加 */}
          <div className='bg-blue-100 w-64 p-4 shadow-md grid-center'>
            <h2 className='font-bold text-xl mb-6 text-blue-800'>
              <Link href='/'>Chat Manager</Link>
            </h2>
            <div className='space-y-4'>
              <div>
                <Link href='/link/chatlist' className='mb-2'>
                  <div className='p-3 bg-white rounded-md hover:bg-blue-50 cursor-pointer transition-colors'>
                    <h3 className='font-medium text-gray-800'>チャット一覧</h3>
                  </div>
                </Link>
              </div>
              <div>
                <Link href='/link/chatlist'>
                  <div className='p-3 bg-white rounded-md hover:bg-blue-50 cursor-pointer transition-colors'>
                    <h3 className='font-medium text-gray-800'>お問い合わせ</h3>
                  </div>
                </Link>
              </div>
            </div>
          </div>

          {/* メインコンテンツエリア - 余白を追加して見やすく */}
          <div className='flex-1 p-6'>{children}</div>
        </div>
      </body>
    </html>
  );
}
